//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWCFServices.RealAuctionDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bids
    {
        public Bids()
        {
            this.Deals = new HashSet<Deals>();
        }
    
        public int BidId { get; set; }
        public Nullable<int> Amount { get; set; }
        public int UserItemId { get; set; }
        public int AuctionItemID { get; set; }
        public Nullable<System.DateTime> CurrentDate { get; set; }
    
        public virtual AuctionItems AuctionItems { get; set; }
        public virtual UserItems UserItems { get; set; }
        public virtual ICollection<Deals> Deals { get; set; }
    }
}
