//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWCFServices.RealAuctionDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostsUItems
    {
        public int PostUItemId { get; set; }
        public string Post { get; set; }
        public Nullable<System.DateTime> PostTime { get; set; }
        public int UserItemId { get; set; }
    
        public virtual UserItems UserItems { get; set; }
    }
}
