//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWCFServices.RealAuctionDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserItems
    {
        public UserItems()
        {
            this.AuctionItems = new HashSet<AuctionItems>();
            this.Bids = new HashSet<Bids>();
            this.Deals = new HashSet<Deals>();
            this.PostsUItems = new HashSet<PostsUItems>();
        }
    
        public int UserItemId { get; set; }
        public string Name { get; set; }
        public string UPassword { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Email { get; set; }
        public byte[] UserImage { get; set; }
    
        public virtual ICollection<AuctionItems> AuctionItems { get; set; }
        public virtual ICollection<Bids> Bids { get; set; }
        public virtual ICollection<Deals> Deals { get; set; }
        public virtual ICollection<PostsUItems> PostsUItems { get; set; }
    }
}
